services:
  bai:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: bai
    user: "0:0"
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: '<0912Helder@@>'
      MSSQL_PID: 'Developer'
      MSSQL_AGENT: 'True'
    ports:
      - "11433:1433"
    volumes:
      - bai_mssql_data:/var/opt/mssql/data
volumes:
  bai_mssql_data:
