POST http://localhost:8080/api/data/incidents
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="incidents"; filename="incidents"
Content-Type: text/csv

< ./incidents.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--

#####

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "teste",
  "password": "jdfdlsk"
}

####

GET http://localhost:8080/api/data


####

GET http://localhost:8080/api/data/last-update


####

GET http://localhost:8080/api/data/ad-audit?start=2024-01-30&end=2024-07-9

####

GET http://localhost:8080/api/data/checkpoint?start=2024-05-30&end=2024-06-1

####

GET http://localhost:8080/api/data/imperva

####

GET http://localhost:8080/api/data/palo-alto

####

GET http://localhost:8080/api/data/darktrace

######

GET  http://localhost:8080/api/config

####

POST  http://localhost:8080/api/config/ldap-server

{
  "url": "",
  "bindDN": "",
  "bindCredentials": "",
  "searchBase": "",
  "searchFilter": "",
}