BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[LDAPServer] (
    [id] NVARCHAR(1000) NOT NULL,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [LDAPServer_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [url] NVARCHAR(1000) NOT NULL,
    [bindDN] NVARCHAR(1000) NOT NULL,
    [bindCredentials] NVARCHAR(1000) NOT NULL,
    [searchBase] NVARCHAR(1000) NOT NULL,
    [searchFilter] NVARCHAR(1000) NOT NULL,
    CONSTRAINT [LDAPServer_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
